### ISSUE TITLE
Any reason for Java 18 instead of 17?

### ISSUE THREAD

**Issue by Dustinhoefer** [namankhurpia/Easy-open-ai#34]
Hey! 

I finally got around to implementing your version of the api.
Unfortunately, I can not run it, since I am running JDK 17.

Any specific reason you are not using the LTS Version 17, but rather 18?

Kind regards
Dustin

**Comment by Dustinhoefer** [comment]
I checked it out, changed to version 17 and tried to build.
Not working :/

Removed maven plugins: sign and javadoc -> building

Using that version -> Caused by: java.lang.ClassNotFoundException: retrofit2.converter.gson.GsonConverterFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
